<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Prueba de Zend Framework.</h1>
              <p>La agenda deberá permitir ingresar nuevos contactos como nombre, uno o más números telefónicos, correo electrónico, dirección.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Leer más</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Agenda de Contactos.</h1>
              <p>La agenda deberá permitir mostrar la lista de contactos existentes, permitir consultar detalles y editarlos.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Leer más</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    
    <div class="container marketing">
    <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">volver arriba</a></p>
        <p>&copy; 2016 Interesse, Test. &middot; <a href="#">Privacida</a> &middot; <a href="#">Términos</a></p>
      </footer>
    </div>