<table class="table">
<thead>
    <tr>
        <th>#</th>
        <th>Nombres</th>
        <th>Dirección</th> 
        <th>Correo electrónico</th>
        <th>Acción</th> 
    </tr> 
</thead>
<tbody>
    <?php foreach ($this->contactos as $item): ?>
    <tr>
        <th scope="row"><?php echo $item['id']; ?></th>
        <td><?php echo $item['nombres'] . ' ' . $item['apellidos']; ?></td>
        <td><?php echo $item['direccion']; ?></td>
        <td><?php echo $item['email']; ?></td>
        <td><a href="#" idrel="<?php echo $item['id']; ?>" ><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
    </tr> 
    <?php endforeach; ?>
</tbody>
</table>